name: isar_community_generator
description: Code generator for the Isar Database. Finds classes annotated with @Collection.
version: 3.2.0-dev.1
repository: https://github.com/isar-community/isar-community
homepage: https://github.com/isar-community/isar-community
issue_tracker: https://github.com/isar-community/isar-community/issues
documentation: https://isar-community.dev
funding:
  - https://github.com/sponsors/vicenterusso/

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  analyzer: ^6.9.0
  build: ^2.3.0
  dart_style: ^3.0.1
  dartx: ^1.1.0
  glob: ^2.0.2
  isar_community: 3.2.0-dev.1
  path: ^1.8.1
  source_gen: ^2.0.0
  xxh3: ^1.0.1

dev_dependencies:
  build_test: ^2.1.5
  matcher: ^0.12.12
  test: ^1.21.0
  very_good_analysis: ^7.0.0

dependency_overrides:
  isar_community:
    path: ../isar_community
